config=yes
vo=gpu-next,
gpu-api=vulkan
hwdec=auto
ad=orender,lavc,
ad-orender-library=orender.dll
ad-orender-bridge-path=harletty_bridge.dll
ad-orender-config=configs/binaural-headphones.yaml
ad-orender-osc=yes
ad-orender-osc-rx-port=9000
ad-orender-osc-port=9001
ad-orender-osc-bind=127.0.0.1
ad-orender-osc-monitor-target=127.0.0.1







